language: ruby
sudo: false
dist: trusty
before_install: gem update --system
matrix:
  include:
  - rvm: ruby-head
    env:
      - LABEL=unit_tests
  - rvm: 2.5.0
    env:
      - LABEL=unit_tests
  - rvm: 2.3.6
    env:
      - LABEL=unit_tests
  - rvm: 2.2.9
    env:
      - LABEL=unit_tests
  - rvm: 2.5.0
    env:
      - LABEL=docker_build_and_push
    services:
      - docker
    branches:
      only:
      - master
    script:
      - docker build -t mozilla/ssh_scan_worker .
      - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      - docker push mozilla/ssh_scan_worker:latest
  - rvm: 2.5.0
    env:
      - LABEL=docker_build_only
    services:
      - docker
    branches:
      except:
      - master
    script:
      - docker build -t mozilla/ssh_scan_worker .