language: ruby
sudo: false
dist: trusty
before_install: gem update --system
matrix:
  include:
  - rvm: 2.6.0
    env:
      - LABEL=unit_tests
  - rvm: 2.5.3
    env:
      - LABEL=unit_tests
  - rvm: 2.5.3
    env:
      - LABEL=docker_build_and_push
    services:
      - docker
    script:
      - chmod u+x ./build_and_deploy_to_dockerhub.sh
      - ./build_and_deploy_to_dockerhub.sh
